<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-3 col-xs-12"></div>
        <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="page-header">
                <h1><?= $page_title ?></h1>
            </div>
            
            <?php if($error): ?>
            <div class="alert alert-danger">
                <strong>Whoops!</strong> Your credential is invalid
            </div>
            <?php endif; ?>
            
            <form method="post">
                <?= $this->form->field('name') ?>
                <?= $this->form->field('password') ?>
                <div class="text-right">
                    <button class="btn btn-default">Login</button>
                </div>
            </form>
        </div>
        <div class="col-md-4 col-sm-3 col-xs-12"></div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>