<?php $this->partial('shared/header'); ?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1>Page not found</h1>
                <p>The requested page can't be found, or you don't have enough credential to view the page.</p>
            </div>
        </div>
    </div>
</div>

<?php $this->partial('shared/footer'); ?>