    <?php if(module_exists('upload')): ?>
    <div class="drawer" id="drawer-media" data-placement="right">
        <div class="drawer-dialog">
            <div class="drawer-body">
                <div class="row">
                    <div class="col-xs-9">
                        <input type="search" class="form-control" placeholder="Find file" id="drawer-media-filter">
                    </div>
                    <form class="col-xs-3 drawer-media-button" id="drawer-media-upload-form">
                        <input type="file" id="drawer-media-upload" title="Upload new file">
                        <button class="btn btn-default" type="button"><i class="fa fa-upload" aria-hidden="true"></i></button>
                    </form>
                </div>
                <hr>
                
                <div class="progress" id="drawer-media-loading">
                    <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <span></span>
                    </div>
                </div>
                
                <div id="drawer-media-search-result"></div>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php if(is_dev()): ?>
    <script src="<?= $this->asset('js/jquery.min.js') ?>"></script>
    <script src="<?= $this->asset('js/tinymce/tinymce.full.js') ?>"></script>
    <script src="<?= $this->asset('js/portal.js') ?>"></script>
    <?php else: ?>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="<?= $this->asset('js/tinymce/tinymce.full.min.js') ?>"></script>
    <script src="<?= $this->asset('js/portal.min.js') ?>?v=1"></script>
    <?php endif; ?>
    <?php if(isset($jses)): ?>
        <?php
            foreach($jses as $js){
                $abs = substr($js, 0, 4) === 'http';
                $js  = $abs ? $js : $this->asset($js);
                echo '<script src="' . $js . '"></script>';
            }
        ?>
    <?php endif; ?>
</body>
</html>