<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
    
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#admin-navigation" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <button href="#" class="btn btn-default navbar-btn navbar-drawer" data-toggle="drawer" data-target="#admin-drawer">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </button>
            
            <a class="navbar-brand" href="<?= $this->router->to('adminHome'); ?>"><?= $nav_title ?></a>
        </div>
        
        <div class="collapse navbar-collapse" id="admin-navigation">
            
            <?php if($admin_submenus): ?>
            <ul class="nav navbar-nav">
            <?php foreach($admin_submenus as $menu): ?>
                <?php if($menu->separator): ?>
                <li role="separator" class="divider"></li>
                <?php endif; ?>
                <li<?= ($menu->active ? ' class="active"' : '') ?>>
                    <a href="<?= $menu->target ?>">
                        <?= $menu->label ?>
                        <?= ($menu->active ? ' <span class="sr-only">(current)</span>' : '') ?>
                    </a>
                </li>
            <?php endforeach; ?>
            </ul>
            <?php endif; ?>
            
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= $this->router->to('siteHome') ?>"><i class="fa fa-globe" aria-hidden="true"></i> Back to site</a></li>
                <?php if($this->user->isLogin()): ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <?= $this->user->fullname ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php if(module_exists('admin-me-setting')): ?>
                        <li>
                            <a href="<?= $this->router->to('adminMeSetting') ?>"><i class="fa fa-sliders" aria-hidden="true"></i> Setting</a>
                        </li>
                        <li role="separator" class="divider"></li>
                        <?php endif; ?>
                        <li>
                            <a href="<?= $this->router->to('adminMeLogout') ?>"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a>
                        </li>
                    </ul>
                </li>
                <?php endif; ?>
            </ul>
            
        </div>
        
    </div>
</nav>

<div class="drawer" id="admin-drawer">
    <div class="drawer-dialog">
        <div class="drawer-header">
            <h4>Admin - <?= $this->config->name ?></h4>
        </div>
        <div class="list-group">
            <?php if($admin_menus): ?>
                <?php foreach($admin_menus as $menu): ?>
                <a class="list-group-item<?= ($menu->active ? ' active' : '') ?>" href="<?= $menu->target ?>">
                    <i class="fa fa-<?= $menu->icon ?>" aria-hidden="true"></i>
                    <?= $menu->label ?>
                </a>
                <?php endforeach; ?>
            <?php endif; ?>
            <a class="list-group-item" href="<?= $this->router->to('siteHome'); ?>">
                <i class="fa fa-globe" aria-hidden="true"></i>
                Back to site
            </a>
        </div>
    </div>
</div>