<div class="form-group<?= ($error?' has-error':'') ?>">
    <?php if(!isset($nolabel) || !$nolabel): ?>
    <label for="<?= $id ?>"><?= $label ?></label>
    <?php endif; ?>
    
    <?php
        $el_attrs = [
            'id'    => $id,
            'name'  => $name,
            'placeholder' => $label,
            'class' => 'form-control'
        ];
        
        if(isset($attrs)){
            foreach($attrs as $key => $val){
                if($key === 'class')
                    $el_attrs['class'].= ' ' . $val;
                else
                    $el_attrs[$key] = $val;
            }
        }
        
        if(count($options) > 10)
            $el_attrs['data-live-search'] = 'true';
        
        // required
        if(isset($rules['required']))
            $el_attrs['required'] = 'required';
        
        $helper = $error ? $error : $desc;
        if($helper)
            $el_attrs['aria-describedby'] = $id . '-help-block';
    ?>
    
    <select <?= array_to_attr($el_attrs); ?>>
        <?php foreach($options as $val => $lab): ?>
        <option value="<?= $val ?>"<?= ($value==$val?' selected="selected"':'') ?>><?= $lab ?></option>
        <?php endforeach; ?>
    </select>
        
    <?php if($helper): ?>
    <span id="<?= $id ?>-help-block" class="help-block"><?= $helper ?></span>
    <?php endif; ?>
    
</div>