<div class="form-group<?= ($error?' has-error':'') ?>">
    <?php if(!isset($nolabel) || !$nolabel): ?>
    <label for="<?= $id ?>"><?= $label ?></label>
    <?php endif; ?>
    
    <?php
        $el_attrs = [
            'id'    => $id,
            'name'  => $name,
            'placeholder' => $label,
            'class' => 'form-control'
        ];
        
        // length
        if(isset($rules['length'])){
            if(isset($rules['length']['min']))
                $el_attrs['minlength'] = $rules['length']['min'];
            if(isset($rules['length']['max']))
                $el_attrs['maxlength'] = $rules['length']['max'];
        }
        
        // required
        if(isset($rules['required']))
            $el_attrs['required'] = 'required';
        
        $helper = $error ? $error : $desc;
        if($helper)
            $el_attrs['aria-describedby'] = $id . '-help-block';
        
        if(isset($attrs)){
            foreach($attrs as $key => $val)
                $el_attrs[$key] = $val;
        }
    ?>
    
    <textarea <?= array_to_attr($el_attrs); ?>><?= $value ?></textarea>
    
    <?php if($helper): ?>
    <span id="<?= $id ?>-help-block" class="help-block"><?= $helper ?></span>
    <?php endif; ?>
</div>