<div class="form-group<?= ($error?' has-error':'') ?>">
    <?php if(!isset($nolabel) || !$nolabel): ?>
    <label for="<?= $id ?>"><?= $label ?></label>
    <?php endif; ?>
    
    <?php
        $el_attrs = [
            'type'  => $type,
            'id'    => $id,
            'name'  => $name,
            'placeholder' => $label,
            'class' => 'form-control'
        ];
        
        if(isset($attrs)){
            foreach($attrs as $key => $val){
                if($key === 'class')
                    $el_attrs['class'].= ' ' . $val;
                else
                    $el_attrs[$key] = $val;
            }
        }
        
        if(!is_null($value) && $type != 'password')
            $el_attrs['value'] = $value;
        
        // alnumdash
        if(isset($rules['alnumdash']))
            $el_attrs['pattern'] = '^[a-zA-Z0-9-]*$';
        
        // length
        if(isset($rules['length'])){
            if(isset($rules['length']['min']))
                $el_attrs['minlength'] = $rules['length']['min'];
            if(isset($rules['length']['max']))
                $el_attrs['maxlength'] = $rules['length']['max'];
        }
        
        // numeric
        if(isset($rules['numeric'])){
            if(isset($rules['numeric']['min']))
                $el_attrs['min'] = $rules['numeric']['min'];
            if(isset($rules['numeric']['max']))
                $el_attrs['max'] = $rules['numeric']['max'];
        }
        
        // regex
        if(isset($rules['regex']))
            $el_attrs['pattern'] = str_replace('!', '', $rules['regex']);
        
        // required
        if(isset($rules['required']))
            $el_attrs['required'] = 'required';
        
        // options
        if($options){
            $el_attrs['list'] = $id . '-datalist';
            $el_attrs['autocomplete'] = 'off';
        }
        
        $helper = $error ? $error : $desc;
        if($helper)
            $el_attrs['aria-describedby'] = $id . '-help-block';
    ?>
    
    <?php if(!isset($icon)): ?>
        <input <?= array_to_attr($el_attrs); ?>>
    <?php else: ?>
    <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-<?= $icon ?>" aria-hidden="true"></i></span>
        <input <?= array_to_attr($el_attrs); ?>>
    </div>
    <?php endif; ?>
    
    <?php if($helper): ?>
    <span id="<?= $id ?>-help-block" class="help-block"><?= $helper ?></span>
    <?php endif; ?>
    
    <?php if($options): ?>
    <datalist id="<?= $id ?>-datalist">
        <?php foreach($options as $val): ?>
        <option value="<?= $val ?>"><?= $val ?></option>
        <?php endforeach; ?>
    </datalist>
    <?php endif; ?>
</div>